const express =require('express')
const BookRouter=require('./controller/books/index')
const CategoryRouter=require('./controller/categories/index')
const DepartmentRouter=require('./controller/departments/index')
const PublisherRouter=require('./controller/publishers/index')
const AuthorRouter=require('./controller/authors/index')
const UserRouter=require('./controller/users/index')
const TokenRouter=require("./controller/tokens/index")
const OrderRouter=require("./controller/orders/index")
const ProductRouter=require("./controller/products/index")
const AddressRouter=require("./controller/address/index")
const ReviewRouter=require("./controller/reviews/index")
const ImageRouter=require("./controller/images/index")
require ('./../services/cache')
const router=express.Router()
router.use("/api/books",BookRouter)
router.use("/api/categories",CategoryRouter)
router.use("/api/departments",DepartmentRouter)
router.use("/api/publishers",PublisherRouter)
router.use("/api/authors",AuthorRouter)
router.use("/api/users",UserRouter)
router.use("/api/tokens",TokenRouter)
router.use("/api/orders",OrderRouter)
router.use("/api/products",ProductRouter)
router.use("/api/address",AddressRouter)
router.use("/api/reviews",ReviewRouter)
router.use("/api/images",ImageRouter)
module.exports=router